### ISSUE TITLE
Homepage wireframe design - milestone 1

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#3]
Design the initial wireframe for the landing page of the web. This landing page is the homepage.
Requirements:

- [x] Overall design wireframe
- [ ] Logo
- [ ] Title
- [x] Menu bar for selecting different recipe categories
- [x] Search bar
- [ ] Art theme decided (discuss with others)
- [x] Color theme decided (discuss with others)
- [ ] Draft art design or visual elements decisions (pics, etc)

This is not a final version of the page, feel free to result to something simple for now. Still, let your creativity bloom, and come up with some sick design if you want to!

Please comment down below whenever a decision for something is made, or if you have good points to make. Other minor discussions and nitty gritty details are to be made in the Discord server. Update this issue regularly to keep it up-to-date with the Discord discussion.

**Comment by yuuni-mikawane** [comment]
Figma file for designing homepage: https://www.figma.com/file/HGHD1tGm1ldls0IMLa6gZn/Meal-Planner?type=design&node-id=0%3A1&mode=design&t=PUmVB3X1jtYhTm9O-1

**DO NOT MODIFY OTHER PEOPLE'S WORK - IF YOU WANT TO IMPROVE AN EXISTING DESIGN, DUPLICATE IT!!!**
