### ISSUE TITLE
Login and signup page for USER - milestone 1

### ISSUE THREAD

**Issue by yuuni-mikawane** [Renji-and-frens/meal-planner-frontend#5]
- [ ] Login form (related issue #7)
- [ ] Signup form (related issue #8)
- [ ] Button to select login/sign up
- [ ] Proper fields (hide/show password, char limits, etc,)

Actual request sending, token acquisition and redirecting will be developed later - this is just a visual preparation.
